matrix:
  include:
    - language: node_js
      node_js: 9.11.1
      before_script:
        - cd frontend
      script:
        - yarn build
      deploy:
        - provider: aws_s3

    - language: python
      python: 3.6
      install:
        - cd api
        - pip3 install pipenv
        - pipenv install
      before_script:
      script:
        - echo "Hello?"
      deploy:
        - provider: heroku
          api_key: ''
