matrix:
  include:
    - language: node_js
      node_js: 9.11.1
      before_script:
      install:
        - cd frontend
        - yarn install
      env:
        - API_ENDPOINT=https://fierce-atoll-11652.herokuapp.com/graphiql
      script:
        - yarn build
      before_deploy:
        - cd build
      deploy:
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          bucket: "timetables-app"
          skip_cleanup: true

    - language: python
      python: 3.6
      install:
        - cd api
        - pip3 install pipenv
        - pipenv install
      before_script:
      script:
        - echo "Hello?"
      deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: fierce-atoll-11652
