matrix:
  include:
    - language: node_js
      node_js: 9.11.1
      dist: "trusty"
      before_script:
      install:
        - sudo add-apt-repository -y ppa:jonathonf/python-3.6
        - sudo apt-get update
        - sudo apt install -y jq python3.6 python3-pip
        - sudo pip3 install awscli
        - cd frontend
        - yarn install
      env:
        - REACT_APP_API_ENDPOINT=https://fierce-atoll-11652.herokuapp.com/graphiql
        - AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
      script:
        - yarn build
      before_deploy:
        - cd build
      deploy:
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          bucket: "timetables-app"
          skip_cleanup: true
          region: ap-southeast-2
      after_deploy:
        - RES=$(aws cloudfront create-invalidation --distribution-id E11EO4PCZRRPGR --paths "/*")
        - echo $RES
        - ID=$(echo $RES | jq .Invalidation.Id -r)
        - "echo ID: $ID"
        - aws cloudfront wait invalidation-completed --distribution-id E11EO4PCZRRPGR --id $ID

    - language: python
      python: 3.6
      install:
        - cd api
        - pip3 install pipenv
        - pipenv install
      before_script:
      script:
        - echo "Hello?"
      deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: fierce-atoll-11652
