matrix:
  include:
    - language: node_js
      before_script:
        - cd frontend
      script:
        - yarn build
      deploy:
        - provider: aws_s3

    - language: python
      before_script:
        - cd api
      script:
      deploy:
        - provider: heroku
          api_key: ''
