matrix:
  include:
    - language: node_js
      deploy:
        - provider: aws_s3
          directory: frontend

    - language: python
      deploy:
        - provider: heroku
          api_key: ''
          directory: api
