matrix:
  include:
    - language: node_js
      before_script:
        - cd frontend
      script:
        - yarn build
      deploy:
        - provider: aws_s3

    - language: python
      python: 3.6
      before_script:
        - cd api
      install:
        - pip3 install pipenv
        - pipenv install
      script:
      deploy:
        - provider: heroku
          api_key: ''
